=== uw-amy-bordenave/asr-imagery-list/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Imagery Source List",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "attribution": {
        "type": "object",
        "properties": {
          "required": {
            "type": "boolean"
          },
          "text": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["required", "text", "url"]
      },
      "description": {
        "type": "string"
      },
      "extent": {
        "type": "object",
        "properties": {
          "max_zoom": {
            "type": "integer"
          },
          "polygon": {
            "type": "array",
            "description": "List of linear rings. Each ring is an array of [lon, lat] pairs. Rings must be closed (first and last coordinate equal).",
            "minItems": 1,
            "items": {
              "type": "array",
              "minItems": 4,
              "items": {
                "type": "array",
                "minItems": 2,
                "maxItems": 2,
                "items": {
                  "type": "number"
                }
              }
            }
          }
        },
        "required": ["max_zoom", "polygon"]
      },
      "icon": {
        "type": "string",
        "format": "uri"
      },
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "type": {
        "type": "string",
        "enum": ["tms", "wmts", "xyz"]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "attribution",
      "description",
      "extent",
      "icon",
      "id",
      "name",
      "type",
      "url"
    ]
  }
}

=== uw-amy-bordenave/asr-imagery-list/imagery/prod/CSUN 2026/CSUN 2026.json
[
    {
        "attribution": {
            "required": true,
            "text": "U.S. Department of Agriculture",
            "url": "https://naip-usdaonline.hub.arcgis.com/"
        },
        "description": "National Agriculture Imagery Program",
        "extent": {
            "max_zoom": 18,
            "polygon": [
                [
                    [-180.0, -85.0511],
                    [180.0, -85.0511],
                    [180.0, 85.0511],
                    [-180.0, 85.0511],
                    [-180.0, -85.0511]
                ]
            ]
        },
        "icon": "https://osmlab.github.io/editor-layer-index/sources/north-america/us/USDA.png",
        "id": "naip",
        "name": "National Agriculture Imagery Program",
        "type": "tms",
        "url": "https://gis.apfo.usda.gov/arcgis/rest/services/NAIP/USDA_CONUS_PRIME/ImageServer/tile/{zoom}/{y}/{x}"
    }
]

=== uw-amy-bordenave/asr-imagery-list/examples/example.json
[
  {
    "attribution": {
      "required": true,
      "text": "© OpenStreetMap contributors",
      "url": "https://www.openstreetmap.org/copyright"
    },
    "description": "OpenStreetMap Standard",
    "extent": {
      "max_zoom": 19,
      "polygon": [
        [
          [-180.0, -85.0511],
          [180.0, -85.0511],
          [180.0, 85.0511],
          [-180.0, 85.0511],
          [-180.0, -85.0511]
        ]
      ]
    },
    "icon": "https://www.openstreetmap.org/assets/osm_logo-4b074077c29e100f40ee64f5177886e36b570d4cc3ab10c7b263003d09642e3f.svg",
    "id": "osm-standard",
    "name": "OpenStreetMap Standard",
    "type": "xyz",
    "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
  }
]
